			<?php
			?>
				<div></div>
			    <table>
			         <caption>Products</caption>
			        <thead>
			            <tr>
			                <td>ID</td>
			                <td>Name</td>

			                <?php if ($block->checkIfCustomerLogged()): ?>
					               <td>SKU</td>
					               <td>Category name</td>
							<?php endif; ?>

			               <td>Image</td>

			                <?php if ($block->checkIfCustomerLogged()): ?>
			               <td>View product</td>
			               <td style="width: 200px;">Recommendation</td>
			                <?php endif; ?>

			          	</tr>
			        </thead>
			        <tbody>
			            	<?php $productCollection = $block->getProductCollection();
								  foreach ($productCollection as $product): ?>

			            <tr class="rowSelected">

			           		<form method="post" class="form_height">
				            	<td><?php echo $product->getEntityId(); ?></td>
				            	<td><?php echo $product->getName(); ?></td>
				            	<?php if ($block->checkIfCustomerLogged()): ?>
				            	<td><?php echo $product->getSku(); ?></td>
				            	<td><?php 	if ($block->getCategoryFromProductId($product->getEntityId()) != null):
				            					echo $block->getCategoryFromProductId($product->getEntityId());
				        					else:
				           						echo 'not found';
				       						endif; ?>
				               
				            	</td>
		            				 <?php  endif; ?>
				           		<td>
				           			<?php if (strlen( $block->getImageFromProductId($product->getEntityId()))!=0): ?>
				           		 <a href="<?php echo $this->getMediaUrl() . "catalog/product/" . $block->getImageFromProductId($product->getEntityId()); ?>">product image</a> 
				           		<?php else: 
			           						echo "not found";
	           						  endif;
				           		?>

				           		</td>
				           			 <?php if ($block->checkIfCustomerLogged()): ?>
				          		<td>
				          			<a href="<?php echo $this->getUrl('statistics/Index/ProductDetailsPage/id/' . $product->getEntityId()); ?>">View product</a>
				            	</td>
				     			<td>
		  							<input type="text" name="recommendation" required="required" style="width: 147px;"><span><input type="submit" name="submit" class="selected" value="save" style="margin-left: 5px;" ></span>
				            		<input type="hidden" name="product_id"
				            		value="<?php echo $product->getEntityId(); ?>">
				                	<input type="hidden" name="customer_id" value="<?php echo $block->getCustomerID(); ?>">
				                	<?php endif; ?>
				            	</td>
			           		</form>
			       		</tr>
			            <?php endforeach; ?>
			       </tbody>
			    </table>
			    <div><?php $block->getImageFromProductId($product->getEntityId()); ?></div>
			<!-- start ajax request -->
			<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous">
			</script>
			<script> 
			    jQuery(document).ready(function() 
			    { 
			 
			    jQuery('tbody tr .rowSelected').on('click',function () {
			/* start */
				    jQuery('.rowSelected').removeClass('rowSelected');
				    jQuery(this).addClass("rowSelected");
			                                                          });
			  
			     jQuery('tbody tr td .selected').on('click',function () 

			    {
			        jQuery('.selected').removeClass('selected');
			        jQuery(this).addClass("selected");
			        alert(jQuery('.rowSelected td input.selected').parent().parent().find('input[name=product_id]').val());
			                var recommendationValue = jQuery('.rowSelected td input.selected').parent().parent().find('input[name=recommendation]').val();
			                var product_id = jQuery('.rowSelected td input.selected').parent().parent().find('input[name=product_id]').val();
			                var customer_id = jQuery('.rowSelected td input.selected').parent().parent().find('input[name=customer_id]').val();
			                alert("recommendationValue: "+recommendationValue +", product_id: "+product_id+", customer_id: "+customer_id);
			                var url = "<?php echo $block->getBaseUrl() . 'statistics/Result/Result/'; ?>";
			                jQuery.ajax({
			                url: url,
			                type: "POST",
			                dataType:"JSON",
			                data: {recommendation:recommendationValue,product_id:product_id,customer_id:customer_id},
			                showLoader: true,
			                cache: false,
			                success: function(response){
			                    console.log("------------------Sucess--------------------");
			                    console.log(response.status);
			                    jQuery('.rowSelected td input[name="recommendation"]').val('');
			                    jQuery('#operation_status').text('');  
			                },
			                error:function(data){
			                    console.log("------------------Error--------------------");
			                    console.log(data.responseText);   
			                    jQuery('#operation_status').text('');
			                }

			    });
			            	return false;
			     });
			   							 	}); 
			</script>
			<!-- end ajax request -->
